### ISSUE TITLE
removing current context group causes errors

### ISSUE THREAD

**Issue by tmack0** [nosarthur/gita#120]
to repro:
gita context test1
gita group rm test1
`gita ll
Traceback (most recent call last):
  File "/usr/local/bin/gita", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/gita/__main__.py", line 438, in main
    args.func(args)
  File "/usr/local/lib/python3.9/site-packages/gita/__main__.py", line 101, in f_ll
    group_repos = utils.get_groups()[args.group]
KeyError: 'test1'
`

patch incoming

**Comment by nosarthur** [comment]
It's in v0.12.6
