### ISSUE TITLE
freeze fails if any repo is not have had commits (or remote)

### ISSUE THREAD

**Issue by blurayne** [nosarthur/gita#133]
`freeze` fails on:
```
Traceback (most recent call last):
  File "/home/ctang/.local/bin/gita", line 11, in <module>
    load_entry_point('gita==0.13.3', 'console_scripts', 'gita')()
  File "/home/ctang/.local/pipx/venvs/gita/lib/python3.8/site-packages/gita/__main__.py", line 499, in main
    args.func(args)
  File "/home/ctang/.local/pipx/venvs/gita/lib/python3.8/site-packages/gita/__main__.py", line 88, in f_freeze
    url = cp.stdout.decode('utf-8').split('\n')[0].split()[1]
IndexError: list index out of range
```

while `ll` does
```
migration develop *_ Merge remote-tracking branch 'origin/readme-fix' into develop (12 months ago)
infra/aa        feature/v2 *_ Fix comment (22 hours ago)
ops/aaa          main        ()
```

After removing  `ops/aaa` from `$HOME/.config/gita/repo_path` it worked again.

**Comment by blurayne** [comment]
https://github.com/nosarthur/gita/pull/134

**Comment by nosarthur** [comment]
Thanks @blurayne for the report and fix. 

I think we can simply leave the url blank since that's also a valid repo situation.

**Comment by nosarthur** [comment]
I have merged the PR and removed the value error when remote URL is not set in v0.13.4. Closing the issue
