### ISSUE TITLE
Issue using shell with pipe on Windows

### ISSUE THREAD

**Issue by vdurante** [nosarthur/gita#173]
I have used the following command: `gita super branch -r --merged | grep -v develop` and it works! But if I change it to `gita shell "git branch -r --merged | grep -v develop"` it fails with the following error:

```
Traceback (most recent call last):
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python39\Scripts\gita-script.py", line 33, in <module>
    sys.exit(load_entry_point('gita==0.15.1', 'console_scripts', 'gita')())
  File "c:\users\vitor\appdata\local\programs\python\python39\lib\site-packages\gita\__main__.py", line 631, in main
    args.func(args)
  File "c:\users\vitor\appdata\local\programs\python\python39\lib\site-packages\gita\__main__.py", line 344, in f_shell
    got = subprocess.run(cmds, cwd=prop['path'], check=True, shell=True,
  File "c:\users\vitor\appdata\local\programs\python\python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'git branch -r --merged | grep -v develop' returned non-zero exit status 255.
```

**Comment by nosarthur** [comment]
Thanks @vdurante 

Maybe we just need to change to `shell=False`

https://github.com/nosarthur/gita/blob/master/gita/__main__.py#L348 

```
        got = subprocess.run(cmds, cwd=prop['path'], check=True, shell=True,
```

**Comment by nosarthur** [comment]
It seems the problem is `check=True`. I have removed in 0.15.2, let me know if it works for you
