### ISSUE TITLE
empty `~/.gita/repo_path` file causes traceback

### ISSUE THREAD

**Issue by nosarthur** [nosarthur/gita#2]
To reproduce:

1. use `gita rm` to remove all repos
1. type any `gita` command

**Comment by mortenfyhn** [comment]
On version 0.6.6 I still get this error. If I remove all repos and run `gita ls` I get this trace:
```
Traceback (most recent call last):
  File "/home/morten/.local/bin/gita", line 10, in <module>
    sys.exit(main())
  File "/home/morten/.local/lib/python3.6/site-packages/gita/__main__.py", line 105, in main
    args.func(args)
  File "/home/morten/.local/lib/python3.6/site-packages/gita/__main__.py", line 18, in f_ls
    for line in utils.describe(repos):
  File "/home/morten/.local/lib/python3.6/site-packages/gita/utils.py", line 175, in describe
    name_width = max(len(n) for n in repos) + 1
ValueError: max() arg is an empty sequence
```

**Comment by nosarthur** [comment]
it's introduced last night for another feature ...
