### ISSUE TITLE
group member becomes obsolete after repo is removed

### ISSUE THREAD

**Issue by nosarthur** [nosarthur/gita#211]
Here I set that group as context, when calling `gita super`, got this traceback 

```
15:35 (quote-mode *) gita $ gita super -q xx
['xx']
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dzhou/src/gita/gita/__main__.py", line 670, in <module>
    main()  # pragma: no cover
  File "/Users/dzhou/src/gita/gita/__main__.py", line 665, in main
    args.func(args)
  File "/Users/dzhou/src/gita/gita/__main__.py", line 368, in f_super
    repos, cmds = utils.parse_repos_and_rest(args.man, args.quote_mode)
  File "/Users/dzhou/src/gita/gita/utils.py", line 495, in parse_repos_and_rest
    chosen[r] = repos[r]
KeyError: 'wikidata'
```

**Comment by nosarthur** [comment]
It seems there are already code to update group config file when `gita rm <repo>` is called. Maybe my setting predates the corresponding change and this traceback won't really occur in reality.

Keep the issue for future reference

**Comment by nosarthur** [comment]
I think I moved the `wikidata` repo in shell, but didn't `gita rm <repo>` (it probably won't allow me to after being moved), thus the repo config file is not updated. `utils.get_repos()` will automatically skip obsolete files.  

We should update the repo and group config if `utils.get_repos()` detects invalid registered repos, i.e., run the same logic in `f_rm`
