### ISSUE TITLE
`gita super diff` not working

### ISSUE THREAD

**Issue by mhagnumdw** [nosarthur/gita#273]
`gita super diff` not working. But `gita super diff --name-status` works fine.

## Error

```
$ gita super diff                   
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/mhagnumdw/.local/lib/python3.12/site-packages/gita/__main__.py", line 825, in <module>
    main()  # pragma: no cover
    ^^^^^^
  File "/home/mhagnumdw/.local/lib/python3.12/site-packages/gita/__main__.py", line 819, in main
    args.func(args)
  File "/home/mhagnumdw/.local/lib/python3.12/site-packages/gita/__main__.py", line 423, in f_super
    f_git_cmd(args)
  File "/home/mhagnumdw/.local/lib/python3.12/site-packages/gita/__main__.py", line 375, in f_git_cmd
    errors = utils.exec_async_tasks(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mhagnumdw/.local/lib/python3.12/site-packages/gita/utils.py", line 422, in exec_async_tasks
    errors = loop.run_until_complete(asyncio.gather(*tasks))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/mhagnumdw/.local/lib/python3.12/site-packages/gita/utils.py", line 396, in run_async
    print(format_output(pipe.decode(), repo_name))
                        ^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 1166: invalid continuation byte
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fe62497a7a0>
Traceback (most recent call last):
  File "/usr/lib64/python3.12/asyncio/base_subprocess.py", line 126, in __del__
  File "/usr/lib64/python3.12/asyncio/base_subprocess.py", line 104, in close
  File "/usr/lib64/python3.12/asyncio/unix_events.py", line 568, in close
  File "/usr/lib64/python3.12/asyncio/unix_events.py", line 592, in _close
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 795, in call_soon
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 541, in _check_closed
RuntimeError: Event loop is closed
```

## Versions
- gita 0.16.6.6
- Python 3.12.3
- Fedora Linux 40 (Workstation Edition) x86_64

**Comment by nosarthur** [comment]
it seems to work on my laptop; is it because your output has unicode characters?

**Comment by mhagnumdw** [comment]
Hi @nosarthur ,

> it seems to work on my laptop; is it because your output has unicode characters?

Yes.

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 1166: invalid continuation byte

![image](https://github.com/nosarthur/gita/assets/17688846/37afa0e0-bd13-4c94-a742-1da6b84b2d97)

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 112785: invalid continuation byte

![image](https://github.com/nosarthur/gita/assets/17688846/bce9224c-5895-4f5c-bca8-4c3952814f6c)

Note: if you run specifying a single repository, something like `gita super repo1 log --patch`, the problem does not occur. If you specify more than one or specify none, the problem occurs.
