### ISSUE TITLE
failure with many repositories on MacOS

### ISSUE THREAD

**Issue by scollovati** [nosarthur/gita#274]
I was not able to find the rigth treshold, but it seems that on MacOS gita is failing in pulling too many repos. When I work on a Windows device with the exact same repositories no issue arises.

```
❯ gita pull
Task was destroyed but it is pending!
task: <Task pending name='Task-240' coro=<BaseSubprocessTransport._connect_pipes() running at /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_subprocess.py:168> wait_for=<Future finished result=None>>
Exception ignored in: <coroutine object BaseSubprocessTransport._connect_pipes at 0x101f7df10>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_subprocess.py", line 189, in _connect_pipes
    waiter.set_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 793, in call_soon
    self._check_closed()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 540, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
```

**Comment by nosarthur** [comment]
just curious, how many repos do you have?

maybe it's related to #232

**Comment by scollovati** [comment]
I have around 160 repos. I cannot use groups since the function for adding repos to a group does not support the recursive `-r` flag.

Maybe it's the batch size. But in my case all pull actions fail, instead in issue #232 the pull is failing just for a subset of them due to a key exchange.
