### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by aboettger** [nosarthur/gita#275]
```shell
❯ pipx install gita --force
--python is ignored when --force is passed. If you want to reinstall gita with /usr/bin/python, run `pipx reinstall gita --python /usr/bin/python` instead.
Installing to existing venv 'gita'
  installed package gita 0.16.6.6, installed using Python 3.12.3
  These apps are now globally available
    - gita
done! ✨ 🌟 ✨
❯ gita
Traceback (most recent call last):
  File "/home/rztab/.local/bin/gita", line 5, in <module>
    from gita.__main__ import main
  File "/home/rztab/.local/pipx/venvs/gita/lib/python3.12/site-packages/gita/__init__.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by nosarthur** [comment]
please try v0.16.7.1
