### ISSUE TITLE
error after upgrade to 0.10.2

### ISSUE THREAD

**Issue by ryshi** [nosarthur/gita#67]
I upgraded gita from 0.9.7 to 0.10.2 , but now I can only get this response by ANY command.
Anything wrong with config?

`Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/gita/__main__.py", line 224, in <module>
    main()  # pragma: no cover
  File "/usr/local/lib/python3.7/site-packages/gita/__main__.py", line 135, in main
    choices=utils.get_repos(),
  File "/usr/local/lib/python3.7/site-packages/gita/utils.py", line 34, in get_repos
    path, name = line.split(',')
ValueError: not enough values to unpack (expected 2, got 1)`

Python version : Python 3.7.3
OS : macOS 10.14.5

**Comment by ryshi** [comment]
the reason is version 0.9.8 broke the format of `~.config/gita/repo_path`
