### ISSUE TITLE
update async code 

### ISSUE THREAD

**Issue by nosarthur** [nosarthur/gita#91]
Currently I'm using py3.6 api in `asyncio`. They are different in py3.7 and won't even work in py3.10

At some point, we need to update them

https://docs.python.org/3.10/whatsnew/3.10.html
https://www.python.org/dev/peps/pep-0619/ (release schedule)

**Comment by DavidRomanovizc** [comment]
Hi there, in which file you need to modify async function?

**Comment by nosarthur** [comment]
You can grep asyncio in the code base. The scope of this case is to bring the async calls up to date with python version 3.10+

**Comment by FernandoMiguel** [comment]
having same issue with python 3.10
```sh
$ gita pull
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/gita/utils.py", line 383, in run_async
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
```
